{
 "title": "Raspberry PI System Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uptime_value",
     "query": "SELECT last(\"value\") FROM \"uptime_value\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thermal_value",
     "query": "SELECT last(\"value\") FROM \"thermal_value\" GROUP BY * ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "cpu",
     "query": "select 100 - last(\"value\") as x from cpu_value where type_instance='idle' AND type='percent' AND $timeFilter group by instance "
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Core Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\") FROM \"thermal_value\" WHERE $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "memory_value",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE $timeFilter GROUP BY time($__interval), \"type_instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "free" },
      { "condition": "OR", "key": "type_instance", "operator": "=", "value": "buffered" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "TX wlan0",
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "wlan0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    },
    {
     "alias": "RX wlan0",
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "wlan0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    },
    {
     "alias": "RX eth0",
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "eth0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    },
    {
     "alias": "TX eth0",
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "eth0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "load" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "load" }
     ]
    }
   ]
  }
 ]
}